language: python # Can use any language here, but if it's not 'python'
                 # it becomes necessary to pass '--user' to pip when installing hererocks.
sudo: false      # Use container-based infrastructure.

env:
  - LUA="lua 5.1"

before_install:
  - pip install hererocks
  - hererocks env --$LUA -rlatest    # Use latest LuaRocks, install into 'env' directory.
  - source env/bin/activate          # Add directory with all installed binaries to PATH.
  - luarocks install luacheck

#install:
#  - luarocks make # Install the rock, assuming there is a rockspec
#                  # in the root of the repository.

script:
  - luacheck scen_edit libs_sb/utils --config .luacheckrc-travis.lua
